version: '3'
services:
  postgres:
    image: "postgres"
    container_name: bd-products
    networks:
      - mynetwork
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=root      
    ports:
      - "5432:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pg-admin-products
    networks:
      - mynetwork
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "54321:80"
    depends_on:
      - postgres

networks:
  mynetwork:
    driver: bridge